name: Add User Story
description: Create a card for someone to tackle.
body:
  - type: textarea
    attributes:
      label: What is the user story?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What the technical details required to implement this?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any other information required for this card?
