name: Build and Test

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build the app
        run: ./gradlew build

      - name: Test the app
        run: ./gradlew test