name: Create APK artifact

on:
  push:
    branches:
      - main

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build artifact
        run: ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: StudyPal APK file
          path: ./composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk